from pydantic import BaseModel
from enum import Enum
from typing import Optional


class ResourceType(str, Enum):
    textbook = "textbook"
    past_paper = "past_paper"
    notes = "notes"
    answers = "answers"
    other = "other"


class ResourceCreateIn(BaseModel):
    subject_id: int
    type: ResourceType
    title: str
    description: Optional[str] = None
    file_url: Optional[str] = None
    storage_path: Optional[str] = None


class ResourceUpdateIn(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    type: Optional[ResourceType] = None
    file_url: Optional[str] = None
    storage_path: Optional[str] = None


class ResourceOut(BaseModel):
    id: int
    subject_id: int
    type: str
    title: str
    description: str | None = None
    is_active: bool = True
    # For private bucket access:
    view_url: str | None = None  # signed URL generated by backend
    # Keep original fields for completeness/debugging (not required by frontend)
    file_url: str | None = None
    storage_path: str | None = None
