from pydantic import BaseModel


class ResourceOut(BaseModel):
    id: int
    subject_id: int
    type: str
    title: str
    description: str | None = None
    # For private bucket access:
    view_url: str | None = None  # signed URL generated by backend
    # Keep original fields for completeness/debugging (not required by frontend)
    file_url: str | None = None
    storage_path: str | None = None
